version: '3'

services:

  mysql:
    image: mysql:5.7.39
    container_name: mysql-instance
    command:
      - "--default-authentication-plugin=mysql_native_password"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
      - "--init-connect='SET NAMES utf8mb4;'"
      - "--innodb_buffer_pool_size=1M"
      - "--query_cache_type=0"
      - "--query-cache-size=0"
      - "--innodb-flush-log-at-trx-commit=0"
      - "--innodb_buffer_pool_instances=1"
      - "--ft_min_word_len=1"
      - "--ft_stopword_file=''"
      - "--innodb-ft-min-token-size=1"
      - "--innodb-ft-enable-stopword=off"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=soulteary
      - LANG=C.UTF-8
    volumes:
      - ./data:/var/lib/mysql:rw
      - ./files:/var/lib/mysql-files:rw